Feature/create transaction service
lditzel94/Skill-Up-Java pull request #12
Opened 2022-11-02 04:17 UTC by MicaLabEGG

Faltan corroborrar si funcionan, ya que necesita del DTO a Modelo comparacion que estaba armando Luciano

2022-11-02 12:57 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/controller/TransactionController.java
> +    public Optional<Transaction> getTransactionDetailById(@PathVariable Integer id ) {
Desde el controller no debería devolverse el objeto Transaction? Dejo otro comentario en relación a esto mas abajo en el TransactionService

2022-11-02 13:00 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/service/implementation/TransactionServiceImpl.java
> +    public Optional<Transaction> getTransactionDetailById(Integer Id){
Acá seria devolver el objeto Transaction, el Optional se obtiene del repository.getById. Una vez obtenido ese Optional, se tendría que chequear si esta vacío o no y accionar en consecuencia. Si no esta vacío, se devuelve el objeto Transaction (si mal no recuerdo, con transaction.get() )

2022-11-02 13:05 UTC, lditzel94 commented on src/main/java/com/alkemy/wallet/controller/TransactionController.java
> +    public Optional<Transaction> getTransactionDetailById(@PathVariable Integer id ) {
En el controller deberían devolver ResponseEntity<TransactionDto>. El optional capturenlo en la capa de servicio y devuelvan al controller los datos ya digeridos

2022-11-02 13:11 UTC, MarianoChun requested changes

2022-11-02 13:11 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/controller/TransactionController.java
> +    public Optional<Transaction> getTransactionDetailById(@PathVariable Integer id ) {
* Change return type to ResponseEntity< Transaction >
* Resolve Optional object in Service Layer

2022-11-03 16:33 UTC, manolomanolero approved these changes

2022-11-03 19:36 UTC, MarianoChun requested changes

2022-11-03 19:36 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/dto/TransactionDetailDto.java
> +        }
Este seria el constructor del detalle de la Transaction, debería tener todos los datos de la misma. Te diría que borres este constructor (porque fijate que esta seteando algunos valores que no van) ya que la anotación @Data ya te brinda uno con todos los parámetros que necesitas

2022-11-03 19:44 UTC, MarianoChun approved these changes

2022-11-03 19:46 UTC, merged