Feature/create-repository-service-controller-fixedtermdeposit
lditzel94/Skill-Up-Java pull request #15
Opened 2022-11-02 14:27 UTC by EMG2311

create repository, service and controller fixedtermdeposit

2022-11-02 15:53 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/dto/FixedTermDepositDto.java
> +}
Si colocas un solo @Getter y @Setter arriba de la declaración de la clase, ya te los crea para todos los atributos

2022-11-02 16:18 UTC, MarianoChun requested changes

2022-11-02 16:18 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/service/implementation/FixedTermDepositServiceImpl.java
> +               System.out.println("the fixed plan entered, it has less than 30 days");
Esto debería arrojar una excepción en vez de imprimir un valor por consola. En DC dejaron información relativa a como implementarla en Spring

2022-11-02 16:18 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/service/implementation/FixedTermDepositServiceImpl.java
> +        return fixedTermDeposit.getFixedTermDepositId();
El valor de retorno al crear un plazo fijo debería ser un objeto FixedTermDeposit, no un id tipo Integer

2022-11-02 16:18 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/service/implementation/FixedTermDepositServiceImpl.java
> +        Long days= ((fixedTermDeposit.getClosingDate().getTime())-fixedTermDeposit.getCreationDate().getTime())/86400000 ; //No anda
No podemos mergear con develop código disfuncional! Comentalo o consulta con alguien como se puede llegar a una solución. En caso de comentarlo, da las razones del por que y que faltaría para que funcione el código

2022-11-02 16:18 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/service/implementation/FixedTermDepositServiceImpl.java
> +        fixedTermDeposit.setCreationDate(timestamp);
Esto podría hacerse con el Mapper que integraron a develop, basicamente permite mapear un Dto a una Entity y viceversa. Dicha conversión tiene que hacerse en el controller y no en el service. El service tendría que recibir un objeto FixedTermDeposit

- El controller recibe un FixedTermDepositDto y devuelve lo mismo, pero al llamar al metodo del service createFixedTermDeposit deberia hacerse el map a entity. 
- Ejemplo: return  service.createFixedTermDeposit (convertToEntity(fixedTermDepositDto ))

2022-11-04 01:31 UTC, MarianoChun requested changes

2022-11-04 01:31 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/service/implementation/FixedTermDepositServiceImpl.java
> +    public FixedTermDeposit createFixedTermDeposit(FixedTermDepositDto fixedTermDepositDto) throws FixedTermDepositException {
Aca deberias retornar tambien el FixedTermDepositDto

2022-11-04 01:31 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/controller/FixedTermDepositController.java
> +    public void createFixedTermDeposit(@Validated @RequestBody FixedTermDepositDto fixedTermDepositDto) throws FixedTermDepositException {
Aca deberias retornar un ResponseEntity<FixedTermDepositDto>. En los demas controllers tenes varios ejemplos de que deberias poner en el return para devolver eso.

2022-11-04 01:31 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/dto/FixedTermDepositDto.java
> +    private Integer account;
Esto tiene que ser de tipo Account, para poder mapearlo a la entity

2022-11-04 02:00 UTC, MarianoChun approved these changes

2022-11-04 02:52 UTC, 4nR3 approved these changes

2022-11-04 02:52 UTC, merged