Feature/endpoint get detail of a user
lditzel94/Skill-Up-Java pull request #22
Opened 2022-11-05 19:44 UTC by MicaLabEGG

2022-11-05 20:08 UTC, manolomanolero approved these changes

2022-11-06 18:29 UTC, MarianoChun requested changes

2022-11-06 18:29 UTC, MarianoChun commented on src/main/java/com/alkemy/wallet/controller/UserController.java
> +    private final UserServiceImpl userServiceImpl;
Habría que sacar la implementación UserServiceImpl, ya que con tener solo la interfaz de UserService spring ya inyecta dicha implementación en el controller

2022-11-06 20:32 UTC, MicaLabEGG commented on src/main/java/com/alkemy/wallet/controller/UserController.java
> +    private final UserServiceImpl userServiceImpl;
listo

2022-11-06 20:39 UTC, MarianoChun approved these changes

2022-11-06 20:42 UTC, merged